services:
#
#  zookeeper:
#    image: bitnami/zookeeper:latest
#    ports:
#      - "2181:2181"
#    environment:
#      ALLOW_ANONYMOUS_LOGIN: yes
#      ZOOKEEPER_SERVER_ID: 1
#      ZOOKEEPER_LISTENER_PORT: 2181
#    volumes:
#      - /var/lib/zookeeper
#    restart: always
#
#
#
#
#      # docker run -d --name kafka -p 9092:9092 apache/kafka:latest
#
#  kafka:
#    image: apache/kafka
#    container_name: kafka
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_PROCESS_ROLES: controller,broker # controller, broker 중 어떤 역할인지 지정 -> 두 역할 모두 수행
#      KAFKA_NODE_ID: 1 # 각 노드의 고유 id
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093 # 자세히 설명필요
#                        # PLAINTEXT://0.0.0.0:9092
#                        #     일반 Kafka 프로듀서/컨슈머와의 통신에 사용되는 포트
#                        #     0.0.0.0은 모든 네트워크 인터페이스에서 요청을 받겠다는 의미
#                        #     어디서 오든 9092로 들어오는 요청을 받을 준비가 되어 있음
#                        # KRaft 모드에서 Kafka 컨트롤러 간 통신을 위한 포트
#                        #     내부 포트이기 때문에 9092포트 말고 다른 포트를 사용
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.25.87:9092
#                        # 클라이언트(프로듀서/컨슈머 등)가 Kafka 브로커에 접속할 때 어떤 주소로 접근해야 하는지를 Kafka가 클라이언트에게 알려주는 값
#      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093 #,2@kafka2:9093,3@kafka3:9093
#                        # KRaft 모드에서 컨트롤러(메타데이터 관리자)들이 서로 통신하고 리더를 선출하기 위한 구성원(투표자)을 지정하는 설정
#                        # [노드ID]@[컨트롤러 리스너 주소:포트]
#                        # 컨트롤러 후보들이 “나 포함 누구랑 투표할지”를 알아야 하며, 그 목록이 바로 KAFKA_CONTROLLER_QUORUM_VOTERS
#      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER # 컨트롤러 리스너 이름 지정
#      KAFKA_CLUSTER_ID: kraft-cluster-1 # 클러스터 고유 id


  zookeeper1:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka1:
    image: bitnami/kafka:3.6.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_ENABLE_KRAFT=no
    depends_on:
      - zookeeper1